site_name: DeepODESurrogates
site_description: DeepODESurrogates is a Python framework for simulating and solving Ordinary Differential Equations (ODEs) using Physics-Informed Neural Networks (PINNs).
site_url: https://frobinou.github.io/DeepODESurrogates/
repo_url: https://github.com/Frobinou/DeepODESurrogates
repo_name: Frobinou/DeepODESurrogates

theme:
  name: material
  language: fr
  font:
    text: Raleway
    code: Source Code Pro
  palette:
    - scheme: default
      primary: deep orange
      accent: orange
      toggle:
        icon: material/brightness-7
        name: Passer en mode sombre
    - scheme: slate
      primary: deep orange
      accent: orange
      toggle:
        icon: material/brightness-4
        name: Passer en mode clair

nav:
  - Accueil: index.md
  - Code: code.md

plugins:
  - search
  - minify:
      minify_html: true
  - mkdocstrings:
      handlers:
        python:
          paths:
            - .
          options:
            docstring_style: google
            show_source: true
  - i18n:
      docs_structure: suffix
      languages:
        - locale: fr
          default: true
          name: Français
          build: true
        - locale: en
          name: English
          build: true

extra:
  alternate:
    - name: Français
      link: /fr/
      lang: fr
    - name: English
      link: /
      lang: en

markdown_extensions:
  - tables
  - admonition
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
